In [1]:
from ising3_10 import Lattice, Ising
import numpy as np
from rich import print

In [2]:
Lattice(size=3, grid=np.array([[1,-1,1],[1,-1,1],[1,-1,2]]))
#i._run(strategy='single', max_iter=3, max_len=6)

Lattice(size=3, p=0.5, grid=array([[ 1, -1,  1],
       [ 1, -1,  1],
       [ 1, -1,  2]]), random_state=None)

In [6]:
i.lattice.random_state

8

In [3]:
import sys
sys.float_info.min

2.2250738585072014e-308

START LOOP

GRID at i: 0

[[ 1  1 -1  1 -1 -1]
 [ 1 -1  1 -1  1  1]
 [-1  1 -1 -1 -1 -1]
 [-1 -1  1 -1 -1  1]
 [ 1  1  1 -1 -1  1]
 [ 1 -1  1  1  1  1]]

FLIPPED at ((2, 3))

GRID at i: 1

[[ 1  1 -1  1 -1 -1]
 [ 1 -1  1 -1  1  1]
 [-1  1 -1  1 -1 -1]
 [-1 -1  1 -1 -1  1]
 [ 1  1  1 -1 -1  1]
 [ 1 -1  1  1  1  1]]

GRID at i: 2

[[ 1  1 -1  1 -1 -1]
 [ 1 -1  1 -1  1  1]
 [-1  1 -1  1 -1 -1]
 [-1 -1  1 -1 -1  1]
 [ 1  1  1 -1 -1  1]
 [ 1 -1  1  1  1  1]]

FLIPPED at ((4, 0))

GRID at i: 3

[[ 1  1 -1  1 -1 -1]
 [ 1 -1  1 -1  1  1]
 [-1  1 -1  1 -1 -1]
 [-1 -1  1 -1 -1  1]
 [-1  1  1 -1 -1  1]
 [ 1 -1  1  1  1  1]]

FLIPPED at ((4, 5))

SystemExit: 0

In [13]:
print(i)

Ising(
    lattice=Lattice(
        size=6,
        p=0.5,
        grid=array([[ 1, -1,  1,  1, -1, -1],
       [ 1, -1, -1, -1, -1,  1],
       [-1,  1, -1,  1, -1,  1],
       [ 1,  1, -1,  1, -1,  1],
       [-1, -1,  1, -1,  1, -1],
       [ 1,  1, -1, -1, -1, -1]]),
        random_state=39
    ),
    temp=255,
    inter=1,
    warmstart=None
)

In [10]:
for s in range(15):
    i = Ising(lattice=Lattice(6,random_state=s))
    des = []
    for r in range(i.lattice.size):
        for j in range(i.lattice.size):
            des.append(i.get_flip(i.lattice, i.temp, i.inter, r,j))
    


(array([-8, -4,  0,  4,  8]), array([ 2, 14, 12,  6,  2]))
(array([-8, -4,  0,  4,  8]), array([ 1, 10, 10, 10,  5]))
(array([-8, -4,  0,  4,  8]), array([ 2, 14, 12,  6,  2]))
(array([-8, -4,  0,  4]), array([ 1,  9, 15, 11]))
(array([-8, -4,  0,  4,  8]), array([ 2, 15,  7,  9,  3]))
(array([-8, -4,  0,  4,  8]), array([ 1,  8, 13, 10,  4]))
(array([-8, -4,  0,  4,  8]), array([ 3, 10,  8, 14,  1]))
(array([-8, -4,  0,  4,  8]), array([ 1,  7, 16, 11,  1]))
(array([-8, -4,  0,  4,  8]), array([ 2, 16, 10,  4,  4]))
(array([-8, -4,  0,  4,  8]), array([ 2,  6, 13, 12,  3]))
(array([-8, -4,  0,  4,  8]), array([ 1,  5, 18,  9,  3]))
(array([-8, -4,  0,  4,  8]), array([ 1, 10, 14, 10,  1]))
(array([-8, -4,  0,  4]), array([ 4,  4, 20,  8]))
(array([-8, -4,  0,  4,  8]), array([ 1, 10, 14, 10,  1]))
(array([-8, -4,  0,  4,  8]), array([ 4,  8, 15,  6,  3]))


In [9]:
np.unique(des, return_counts=True)

(array([-8, -4,  0,  4,  8]), array([ 1, 10, 10, 10,  5]))

In [12]:
rng = np.random.default_rng(1)
rng.random()

0.5118216247002567

In [5]:
try:
    print("nope")
    l = Lattice(size = 3, grid=np.array(2))
finally:
    print("yep")
    l = Lattice(size = 10)



nope
yep


AssertionError: Values of spin must be +1 or -1 .

In [1]:
from collections import deque

In [17]:
a = deque(maxlen=2)

In [21]:
a.append("hola")
a.append("adios")
a.append("gello")
a.append("hola")
a

deque(['gello', 'hola'])

In [24]:
import numpy as np


array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [27]:
%%timeit 
checkerboard = (np.indices((4,4)).sum(axis=0) % 2)
np.transpose(np.where(checkerboard == 1))

15.5 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
checkerboard = (np.indices((4,4)).sum(axis=0) % 2)
np.transpose(np.where(checkerboard == 0))

array([[0, 0],
       [0, 2],
       [1, 1],
       [1, 3],
       [2, 0],
       [2, 2],
       [3, 1],
       [3, 3]])

In [29]:
a = 3
b = 'alf'

'_'.join([f'{a}', b])

'3_alf'

In [1]:
import ising3_9 as i9

In [2]:
import numpy as np

l1 = i9.Lattice(3,0.5, 0)


In [3]:
i = i9.Ising2D(l1, 255)

In [4]:
i._run('single', 10000, 3)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'deque': Cannot determine Numba type of <class 'type'>

File "ising3_9.py", line 377:
    def _run(self, strategy:str, max_iter:int, max_len:int):
        history = deque(maxlen=max_len)
        ^
 

This error may have been caused by the following argument(s):
- argument 0: Cannot determine Numba type of <class 'ising3_9.Ising2D'>
