In [3]:
from ising3_10 import Lattice, Ising
import numpy as np
from rich import print

In [4]:
i = Ising()
print(i)
i._run(strategy='single', max_iter=3, max_len=6)

Ising(
    lattice=Lattice(
        size=32,
        p=0.5,
        grid=array([[ 1,  1, -1,  1, -1, -1],
       [ 1, -1,  1, -1,  1,  1],
       [-1,  1, -1,  1, -1, -1],
       [-1, -1,  1, -1, -1,  1],
       [-1,  1,  1, -1, -1, -1],
       [ 1, -1,  1,  1,  1,  1]]),
        random_state=2
    ),
    temp=255,
    inter=1,
    warmstart=None
)

START LOOP

GRID at i: 0

[[ 1  1 -1  1 -1 -1]
 [ 1 -1  1 -1  1  1]
 [-1  1 -1  1 -1 -1]
 [-1 -1  1 -1 -1  1]
 [-1  1  1 -1 -1 -1]
 [ 1 -1  1  1  1  1]]

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/Users/idal/Documents/GitHub/ising/ising3_10.py", line 355, in _run
    self.update_grid(self.strategy())
  File "/Users/idal/Documents/GitHub/ising/ising3_10.py", line 246, in update_grid
    self.update_grid_nmb(self.lattice, self.flip, points)
  File "/Users/idal/Documents/GitHub/ising/ising3_10.py", line 241, in update_grid_nmb
    if get_flip_nmb(lattice, flip, point[0], point[1]):
  File "/Users/idal/Documents/GitHub/ising/ising3_10.py", line 135, in get_flip_nmb
    neighbors_contrib += lattice.grid[ids[0], ids[1]]
IndexError: index 6 is out of bounds for axis 0 with size 6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/idal/Documents/GitHub/ising/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/w6/9n15lyxs6r58r0ld7jlcyskr0000gp/T/ipykernel_27722/9

TypeError: object of type 'NoneType' has no len()

In [21]:
print(i)

Ising(
    lattice=Lattice(
        size=6,
        p=0.5,
        grid=array([[ 1,  1, -1,  1, -1, -1],
       [ 1, -1,  1, -1,  1,  1],
       [-1,  1, -1,  1, -1, -1],
       [-1, -1,  1, -1, -1,  1],
       [-1,  1,  1, -1, -1, -1],
       [ 1, -1,  1,  1,  1,  1]]),
        random_state=5
    ),
    temp=255,
    inter=1,
    warmstart=None
)

START LOOP

GRID at i: 0

[[ 1  1 -1  1 -1 -1]
 [ 1 -1  1 -1  1  1]
 [-1  1 -1 -1 -1 -1]
 [-1 -1  1 -1 -1  1]
 [ 1  1  1 -1 -1  1]
 [ 1 -1  1  1  1  1]]

FLIPPED at ((2, 3))

GRID at i: 1

[[ 1  1 -1  1 -1 -1]
 [ 1 -1  1 -1  1  1]
 [-1  1 -1  1 -1 -1]
 [-1 -1  1 -1 -1  1]
 [ 1  1  1 -1 -1  1]
 [ 1 -1  1  1  1  1]]

GRID at i: 2

[[ 1  1 -1  1 -1 -1]
 [ 1 -1  1 -1  1  1]
 [-1  1 -1  1 -1 -1]
 [-1 -1  1 -1 -1  1]
 [ 1  1  1 -1 -1  1]
 [ 1 -1  1  1  1  1]]

FLIPPED at ((4, 0))

GRID at i: 3

[[ 1  1 -1  1 -1 -1]
 [ 1 -1  1 -1  1  1]
 [-1  1 -1  1 -1 -1]
 [-1 -1  1 -1 -1  1]
 [-1  1  1 -1 -1  1]
 [ 1 -1  1  1  1  1]]

FLIPPED at ((4, 5))

SystemExit: 0

In [13]:
print(i)

Ising(
    lattice=Lattice(
        size=6,
        p=0.5,
        grid=array([[ 1, -1,  1,  1, -1, -1],
       [ 1, -1, -1, -1, -1,  1],
       [-1,  1, -1,  1, -1,  1],
       [ 1,  1, -1,  1, -1,  1],
       [-1, -1,  1, -1,  1, -1],
       [ 1,  1, -1, -1, -1, -1]]),
        random_state=39
    ),
    temp=255,
    inter=1,
    warmstart=None
)

In [10]:
for s in range(15):
    i = Ising(lattice=Lattice(6,random_state=s))
    des = []
    for r in range(i.lattice.size):
        for j in range(i.lattice.size):
            des.append(i.get_flip(i.lattice, i.temp, i.inter, r,j))
    


(array([-8, -4,  0,  4,  8]), array([ 2, 14, 12,  6,  2]))
(array([-8, -4,  0,  4,  8]), array([ 1, 10, 10, 10,  5]))
(array([-8, -4,  0,  4,  8]), array([ 2, 14, 12,  6,  2]))
(array([-8, -4,  0,  4]), array([ 1,  9, 15, 11]))
(array([-8, -4,  0,  4,  8]), array([ 2, 15,  7,  9,  3]))
(array([-8, -4,  0,  4,  8]), array([ 1,  8, 13, 10,  4]))
(array([-8, -4,  0,  4,  8]), array([ 3, 10,  8, 14,  1]))
(array([-8, -4,  0,  4,  8]), array([ 1,  7, 16, 11,  1]))
(array([-8, -4,  0,  4,  8]), array([ 2, 16, 10,  4,  4]))
(array([-8, -4,  0,  4,  8]), array([ 2,  6, 13, 12,  3]))
(array([-8, -4,  0,  4,  8]), array([ 1,  5, 18,  9,  3]))
(array([-8, -4,  0,  4,  8]), array([ 1, 10, 14, 10,  1]))
(array([-8, -4,  0,  4]), array([ 4,  4, 20,  8]))
(array([-8, -4,  0,  4,  8]), array([ 1, 10, 14, 10,  1]))
(array([-8, -4,  0,  4,  8]), array([ 4,  8, 15,  6,  3]))


In [9]:
np.unique(des, return_counts=True)

(array([-8, -4,  0,  4,  8]), array([ 1, 10, 10, 10,  5]))

In [12]:
rng = np.random.default_rng(1)
rng.random()

0.5118216247002567

In [5]:
try:
    print("nope")
    l = Lattice(size = 3, grid=np.array(2))
finally:
    print("yep")
    l = Lattice(size = 10)



nope
yep


AssertionError: Values of spin must be +1 or -1 .

In [1]:
from collections import deque

In [17]:
a = deque(maxlen=2)

In [21]:
a.append("hola")
a.append("adios")
a.append("gello")
a.append("hola")
a

deque(['gello', 'hola'])

In [24]:
import numpy as np


array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [27]:
%%timeit 
checkerboard = (np.indices((4,4)).sum(axis=0) % 2)
np.transpose(np.where(checkerboard == 1))

15.5 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
checkerboard = (np.indices((4,4)).sum(axis=0) % 2)
np.transpose(np.where(checkerboard == 0))

array([[0, 0],
       [0, 2],
       [1, 1],
       [1, 3],
       [2, 0],
       [2, 2],
       [3, 1],
       [3, 3]])

In [29]:
a = 3
b = 'alf'

'_'.join([f'{a}', b])

'3_alf'