In [1]:
from ising3_10 import Lattice, Ising
import numpy as np

In [14]:
rng = np.random.default_rng(0)
g = 2*rng.binomial(1, p=0.9, size=[1001]*2)-1
np.unique(g, return_counts=True)

(array([-1,  1]), array([100522, 901479]))

In [3]:
Lattice(1)

Lattice(size=1, p=0.5, grid=array([[-1]]), random_state=None)

In [8]:
Ising(temp=25500,inter=-23.1)

Ising(lattice=Lattice(size=32, p=0.5, grid=array([[ 1, -1, -1, ...,  1,  1, -1],
       [-1,  1,  1, ..., -1, -1,  1],
       [-1,  1, -1, ...,  1,  1,  1],
       ...,
       [-1,  1, -1, ..., -1,  1,  1],
       [ 1,  1,  1, ...,  1,  1, -1],
       [ 1, -1,  1, ...,  1, -1,  1]]), random_state=0), temp=25500, inter=-23.1)

In [9]:
l = Lattice(4)

In [13]:
np.mod((0,4),4)

array([0, 0])

In [11]:
l.grid[0,3] = 9
l.grid

array([[-1,  1, -1,  9],
       [ 1,  1,  1, -1],
       [-1, -1, -1,  1],
       [-1, -1,  1, -1]])

In [5]:
try:
    print("nope")
    l = Lattice(size = 3, grid=np.array(2))
finally:
    print("yep")
    l = Lattice(size = 10)



nope
yep


AssertionError: Values of spin must be +1 or -1 .