In [1]:
from ising3_10 import Lattice, Ising
import numpy as np

In [2]:
i = Ising(lattice=Lattice(6,random_state=1))

In [3]:
i.lattice.grid

array([[ 1,  1, -1,  1, -1, -1],
       [ 1, -1,  1, -1,  1,  1],
       [-1,  1, -1, -1, -1, -1],
       [-1, -1,  1, -1, -1,  1],
       [ 1,  1,  1, -1, -1,  1],
       [ 1, -1,  1,  1,  1,  1]])

In [4]:
list_of_spins = [(1,1), (2,3), (4,3)]
i.update_grid(list_of_spins)
i.lattice.grid

array([[ 1,  1, -1,  1, -1, -1],
       [ 1, -1,  1, -1,  1,  1],
       [-1,  1, -1,  1, -1, -1],
       [-1, -1,  1, -1, -1,  1],
       [ 1,  1,  1,  1, -1,  1],
       [ 1, -1,  1,  1,  1,  1]])

In [11]:
index_flip = 0.25*i.lattice.grid[1,1]*4 + 2
index_flip

3.0

In [9]:
k = 1.381e-16 # eV/K
k

1.381e-16

In [10]:
1/(i.temp*k)

28396586730275.023

In [11]:
np.exp(-8/(i.temp*k))

0.0

In [5]:
i.flip

(True, True, True, 8.74175144307033e-80, 7.641821829242221e-159)

In [10]:
for s in range(15):
    i = Ising(lattice=Lattice(6,random_state=s))
    des = []
    for r in range(i.lattice.size):
        for j in range(i.lattice.size):
            des.append(i.get_flip(i.lattice, i.temp, i.inter, r,j))
    


(array([-8, -4,  0,  4,  8]), array([ 2, 14, 12,  6,  2]))
(array([-8, -4,  0,  4,  8]), array([ 1, 10, 10, 10,  5]))
(array([-8, -4,  0,  4,  8]), array([ 2, 14, 12,  6,  2]))
(array([-8, -4,  0,  4]), array([ 1,  9, 15, 11]))
(array([-8, -4,  0,  4,  8]), array([ 2, 15,  7,  9,  3]))
(array([-8, -4,  0,  4,  8]), array([ 1,  8, 13, 10,  4]))
(array([-8, -4,  0,  4,  8]), array([ 3, 10,  8, 14,  1]))
(array([-8, -4,  0,  4,  8]), array([ 1,  7, 16, 11,  1]))
(array([-8, -4,  0,  4,  8]), array([ 2, 16, 10,  4,  4]))
(array([-8, -4,  0,  4,  8]), array([ 2,  6, 13, 12,  3]))
(array([-8, -4,  0,  4,  8]), array([ 1,  5, 18,  9,  3]))
(array([-8, -4,  0,  4,  8]), array([ 1, 10, 14, 10,  1]))
(array([-8, -4,  0,  4]), array([ 4,  4, 20,  8]))
(array([-8, -4,  0,  4,  8]), array([ 1, 10, 14, 10,  1]))
(array([-8, -4,  0,  4,  8]), array([ 4,  8, 15,  6,  3]))


In [9]:
np.unique(des, return_counts=True)

(array([-8, -4,  0,  4,  8]), array([ 1, 10, 10, 10,  5]))

In [12]:
rng = np.random.default_rng(1)
rng.random()

0.5118216247002567

In [5]:
try:
    print("nope")
    l = Lattice(size = 3, grid=np.array(2))
finally:
    print("yep")
    l = Lattice(size = 10)



nope
yep


AssertionError: Values of spin must be +1 or -1 .